package com.ps
 
import com.ps.util.TransactionStatus;
import com.ps.entity.Transaction;
import com.ps.util.TranObjectContainer;

rule "Velocity Reject"
    when
        TranObjectContainer(newTransaction.status == TransactionStatus.INIT, $tran:newTransaction, $oldTrans:oldTransactions)
    then
        System.out.println( "inside Velocity Eligible rule - old transactions size: "+$oldTrans.size());
  
  		if($oldTrans.size()>2) {
        	$tran.setStatus(TransactionStatus.REJECT);      
        } 
end